version: '3.9'


services:
  # mongoDB services 
  mongo_db:
    container_name: db_container # optional
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes: 
      - mongo_db:/data/db
  nginx: 
    depends_on:
      - api
      - client
    restart: always
    build: 
      dockerfile: Dockerfile 
      context: ./nginx
    ports: 
      - 80:80
  api:
    build: ./server
    ports:
      - 8000:8000
    environment:
      MONGODB_URI: mongodb://mongo_db:27017 # service name or container name
      JWT_SECRET: loremdsfdsfdsfdsfdsfdsfdsfdsf
    depends_on:
      - mongo_db
  client: 
    stdin_open: true
    build: ./client
    volumes: 
      - /app/node_modules
      - ./client:/app
volumes: 
  mongo_db: {}

