version: '3.9'


services:
  # mongoDB services 
  mongo_db:
    container_name: db_container # optional
    image: mongo:latest
    restart: always
    volumes: 
      - mongo_db:/data/db

  api:
    build: ./server
    ports:
      - 8000:8000
    environment:
      MONGODB_URI: mongodb://mongo_db:27017 # service name or container name
      JWT_SECRET: loremdsfdsfdsfdsfdsfdsfdsfdsf
    depends_on:
      - mongo_db
volumes: 
  mongo_db: {}

