version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:8000"  # Map host port 3001 to container port 8000

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Map host port 80 to container port 80
    volumes:
      - ./nginx-config:/etc/nginx/conf.d  # Mount the NGINX configuration
      - ./client/build:/var/www/html  # Mount the built React app
    depends_on:
      - client
